version: 2
updates:
  - package-ecosystem: gomod
    directory: /srv/web/
    schedule:
      interval: daily
      time: "05:30"
      timezone: Europe/Zurich

  - package-ecosystem: npm
    directory: /client/
    schedule:
      interval: daily
      time: "05:30"
      timezone: Europe/Zurich

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:30"
      timezone: Europe/Zurich

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: "05:30"
      timezone: Europe/Zurich
