[package]
name = "embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.95", features = ["backtrace"] }
candle-core = "0.8.1"
candle-nn = "0.8.1"
candle-transformers = "0.8.1"
clap = { version = "4.5.26", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tokenizers = { version = "0.21.0", default-features = false, features = ["onig"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
warp = "0.3.7"
