[package]
name = "embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
candle-core = "0.6.0"
candle-nn = "0.6.0"
candle-transformers = "0.6.0"
clap = { version = "4.5.17", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokenizers = { version = "0.20.0", default-features = false, features = ["onig"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
warp = "0.3.7"
