[package]
name = "embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
candle-core = "0.6.0"
candle-nn = "0.6.0"
candle-transformers = "0.6.0"
clap = { version = "4.5.9", features = ["derive"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tokenizers = { version = "0.19.1", default-features = false, features = ["onig"] }
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
warp = "0.3.7"
