[package]
name = "embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.93", features = ["backtrace"] }
candle-core = "0.8.1"
candle-nn = "0.7.2"
candle-transformers = "0.7.2"
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
tokenizers = { version = "0.20.3", default-features = false, features = ["onig"] }
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
warp = "0.3.7"
